apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuseki
  template:
    metadata:
      labels:
        app: fuseki
    spec:
      containers:
        - name: fuseki
          image: stain/jena-fuseki
          ports:
            - containerPort: 3030
          env:
            - name: ADMIN_PASSWORD
              value: "admin"
            - name: JVM_ARGS
              value: "-Xmx2g"
            - name: FUSEKI_DATASET_1
              value: "electricityprice-canton"
            - name: TDB
              value: "2"
          volumeMounts:
            - name: fuseki-database
              mountPath: /fuseki/databases
            - name: fuseki-data
              mountPath: /fuseki/data
            - name: fuseki
              mountPath: /fuseki
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      initContainers:
        - name: download-dataset
          image: stain/jena-fuseki
          command:
            - "sh"
            - "-c"
            - /scripts/load-dataset.sh
          volumeMounts:
            - name: fuseki-database
              mountPath: /fuseki/databases
            - name: fuseki-data
              mountPath: /fuseki/data
            - name: fuseki-scripts
              mountPath: /scripts
      volumes:
        - name: fuseki
          emptyDir: {}
        - name: fuseki-database
          emptyDir: {}
        - name: fuseki-data
          emptyDir: {}
        - name: fuseki-scripts
          configMap:
            name: fuseki-scripts
            defaultMode: 0755
