apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fuseki'
        static_configs:
          - targets: ['fuseki:3030']
        metrics_path: "/$/metrics"
        basic_auth:
          username: "admin"
          password: "admin"
