version: "3"

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
      - FUSEKI_DATASET_1=<dataset_name>
      - TDB=2
    volumes:
      - ../data/fuseki/databases:/fuseki/databases
      - fuseki-data:/fuseki

  yasgui:
    image: erikap/yasgui
    container_name: yasgui
    ports:
      - "3000:80"
    environment:
      DEFAULT_SPARQL_ENDPOINT: "http://localhost:3030/<dataset_name>/sparql"

  graph-explorer:
    image: public.ecr.aws/neptune/graph-explorer:latest-SNAPSHOT
    container_name: graph-explorer
    ports:
      - "80:80"
    environment:
      HOST: localhost
      PROXY_SERVER_HTTPS_CONNECTION: false
      GRAPH_EXP_HTTPS_CONNECTION: false

volumes:
  fuseki-data:
